/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bill;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author m17
 */
public class discharge extends javax.swing.JFrame {

    public String reg_num,status = "Cured";
    public void get_reg(String s) {
        reg_num = s;
        r.setText(reg_num);
        String u ="asd";
        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement ss=(Statement)con.createStatement();
            ResultSet rs;
            
            rs = ss.executeQuery("Select * from patient where Reg_No = '"+reg_num+"'");
            while(rs.next()){
                u = rs.getString("Name");
            }
        }catch (Exception e) {
        }
        name.setText(u);
    }
    
    /**
     * Creates new form discharge
     */
    public discharge() {
        initComponents();
        String p="gh";
        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement s=(Statement)con.createStatement();
            ResultSet rs;
            rs = s.executeQuery("Select * from organization");
            while(rs.next()){
                p = rs.getString("Org_Name");
            }
            
        }catch (Exception e) {
        }
        host.setText(p);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        int screenWidth = dimension.width;
        int screenHeight = dimension.height;
        setSize(dimension);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
        JLabel background=new JLabel(new ImageIcon(getClass().getResource("/bill/bkground.jpg")));
        add(background);
        background.setLayout(new FlowLayout());
        Date date = new Date();
        jLabel5.setText(date.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        host = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        r = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 500));
        getContentPane().setLayout(null);

        host.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        host.setForeground(new java.awt.Color(255, 255, 0));
        host.setText("D.M.H. Hospital");
        getContentPane().add(host);
        host.setBounds(440, 80, 238, 41);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Patient's Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 240, 130, 22);

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(51, 204, 0));
        name.setText("Name");
        getContentPane().add(name);
        name.setBounds(600, 240, 190, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Registration Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(345, 280, 170, 22);

        r.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r.setForeground(new java.awt.Color(51, 153, 0));
        r.setText(reg_num);
        getContentPane().add(r);
        r.setBounds(600, 280, 110, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Date of Discharge");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(349, 330, 150, 22);

        d.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        d.setForeground(new java.awt.Color(51, 204, 0));
        getContentPane().add(d);
        d.setBounds(600, 330, 120, 28);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(153, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cured", "Dead" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(600, 380, 65, 23);

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Print Bill");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 470, 100, 25);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 204));
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(770, 70, 330, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String k = d.getText();
        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement ss=(Statement)con.createStatement();
            ss.executeUpdate("Update patient SET Exit_Date= '"+k+"' where Reg_No = '"+reg_num+"'");
        }catch (Exception e) {
        }
        print_bill obj1 = new print_bill();
        obj1.get_reg_num(reg_num);
        obj1.get_status(status);
        setVisible(false);
        obj1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        status = jComboBox1.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField d;
    private javax.swing.JLabel host;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel name;
    private javax.swing.JLabel r;
    // End of variables declaration//GEN-END:variables
}
