/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bill;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author m17
 */
public class get_info extends javax.swing.JFrame {

    /* my code is from here */
    int flag;
    public void set_flag(int val) {
        flag = val;
    }
    /* my code ends */
    /**
     * Creates new form get_info
     */
    public get_info() {
        initComponents();
        String p="gh";
        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement s=(Statement)con.createStatement();
            ResultSet rs;
            rs = s.executeQuery("Select * from organization");
            while(rs.next()){
                p = rs.getString("Org_Name");
            }
            
        }catch (Exception e) {
        }
        host.setText(p);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        int screenWidth = dimension.width;
        int screenHeight = dimension.height;
        setSize(dimension);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
        JLabel background=new JLabel(new ImageIcon(getClass().getResource("/bill/bkground.jpg")));
        add(background);
        background.setLayout(new FlowLayout());
        Date date = new Date();
        jLabel3.setText(date.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        host = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        reg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        host.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        host.setForeground(new java.awt.Color(255, 255, 51));
        host.setText("D.M.H Hospital");
        getContentPane().add(host);
        host.setBounds(520, 70, 259, 41);

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Enter Patient Reg. Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(330, 260, 350, 29);

        reg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        reg.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(reg);
        reg.setBounds(720, 260, 180, 28);

        jButton1.setBackground(new java.awt.Color(153, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(630, 350, 65, 25);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 153));
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(870, 70, 300, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String temp = reg.getText();
        String p="asd";
        int f =0;
        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement s=(Statement)con.createStatement();
            ResultSet rs;
            rs = s.executeQuery("Select * from patient");
            while(rs.next()){
                p = rs.getString("Reg_No");
                if(p.compareTo(temp) == 0){
                    f = 1;
                    break;
                }
                
            }
            
        }catch (Exception e) {
    }
        if (f == 0) {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"This Regestration Number does not exist.","Warning",JOptionPane.WARNING_MESSAGE);
        } else {
            if (flag == 1) {
                update obj1 = new update();
                obj1.get_reg(temp);
                setVisible(false);
                obj1.setVisible(true);
            } else {
                discharge obj2 = new discharge();
                obj2.get_reg(temp);
                setVisible(false);
                obj2.setVisible(true);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel host;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField reg;
    // End of variables declaration//GEN-END:variables
}
