/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bill;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.ResultSet;
import java.util.*;

public class homepage extends javax.swing.JFrame {
    String uname,str;
     
    public void get_uname(String s) {
        uname = s;
    }
    public homepage() {
       // setSize(400,768);
        
        initComponents();
        String p="blah blah";
       /* try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement s=(Statement)con.createStatement();
            ResultSet rs;
            rs = s.executeQuery("Select * from organization");
            while(rs.next()){
                p = rs.getString("Org_Name");
            }
            
        }catch (Exception e) {
        }*/
        host.setText(p);
       /* try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement s=(Statement)con.createStatement();
            ResultSet rs;
            
            
            rs = s.executeQuery("Select * from organization");
            while(rs.next()){
                str = rs.getString("Org_Name");
            }
        } catch (Exception e) {
    }*/
        setTitle("blah blah Sails Portal");
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        int screenWidth = dimension.width;
        int screenHeight = dimension.height;
        setSize(dimension);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
        JLabel background=new JLabel(new ImageIcon(getClass().getResource("/bill/image2.jpg")));
        background.setSize(800, 800);
        add(background);
        background.setLayout(new FlowLayout());
        Date date = new Date();
        jLabel1.setText(date.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        orgdetails = new javax.swing.JButton();
        newentry = new javax.swing.JButton();
        host = new javax.swing.JLabel();
        bed = new javax.swing.JButton();
        existing = new javax.swing.JButton();
        discharge = new javax.swing.JButton();
        signout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        changepasswd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        orgdetails.setBackground(new java.awt.Color(240, 163, 97));
        orgdetails.setText("Update Stock Details");
        orgdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgdetailsActionPerformed(evt);
            }
        });
        getContentPane().add(orgdetails);
        orgdetails.setBounds(270, 150, 200, 23);

        newentry.setBackground(new java.awt.Color(240, 163, 97));
        newentry.setText("New Stock Entry");
        newentry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newentryActionPerformed(evt);
            }
        });
        getContentPane().add(newentry);
        newentry.setBounds(580, 150, 200, 23);

        host.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        host.setForeground(new java.awt.Color(255, 255, 0));
        host.setText("blah blah Sales");
        getContentPane().add(host);
        host.setBounds(520, 20, 290, 30);

        bed.setBackground(new java.awt.Color(240, 163, 97));
        bed.setText("Show Stock Details");
        bed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bedActionPerformed(evt);
            }
        });
        getContentPane().add(bed);
        bed.setBounds(880, 150, 200, 23);

       /* existing.setBackground(new java.awt.Color(240, 163, 97));
        existing.setText("Existing Patient Updates");
        existing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existingActionPerformed(evt);
            }
        });
        getContentPane().add(existing);
        existing.setBounds(580, 210, 200, 23);*/

        discharge.setBackground(new java.awt.Color(240, 163, 97));
        discharge.setText("Bill Order ");
        discharge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dischargeActionPerformed(evt);
            }
        });
        getContentPane().add(discharge);
        discharge.setBounds(580, 270, 200, 23);

        signout.setBackground(new java.awt.Color(255, 255, 255));
        signout.setText("Signout");
        signout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutActionPerformed(evt);
            }
        });
        getContentPane().add(signout);
        signout.setBounds(10, 20, 100, 23);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hii");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(987, 20, 232, 20);

        changepasswd.setBackground(new java.awt.Color(240, 163, 97));
        changepasswd.setText("Change Password");
        changepasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepasswdActionPerformed(evt);
            }
        });
        getContentPane().add(changepasswd);
        changepasswd.setBounds(270, 210, 200, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newentryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newentryActionPerformed
        setVisible(false);
        new new_entry().setVisible(true);
    }//GEN-LAST:event_newentryActionPerformed

    private void existingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existingActionPerformed
        setVisible(false);
        get_info obj1 = new get_info();
        obj1.set_flag(1);
        obj1.setVisible(true);
    }//GEN-LAST:event_existingActionPerformed

    private void signoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutActionPerformed
        setVisible(false);
        new login().setVisible(true);
    }//GEN-LAST:event_signoutActionPerformed

    private void dischargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dischargeActionPerformed
        get_info obj1 = new get_info();
        obj1.set_flag(2);
        setVisible(false);
        obj1.setVisible(true);
    }//GEN-LAST:event_dischargeActionPerformed

    private void bedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bedActionPerformed
        setVisible(false);
        new show_bed().setVisible(true);
    }//GEN-LAST:event_bedActionPerformed

    private void orgdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgdetailsActionPerformed
        setVisible(false);
        new orgupdate().setVisible(true);
    }//GEN-LAST:event_orgdetailsActionPerformed

    private void changepasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepasswdActionPerformed
        passwd obj1 = new passwd();
        obj1.get_uname(uname);
        setVisible(false);
        obj1.setVisible(true);
    }//GEN-LAST:event_changepasswdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bed;
    private javax.swing.JButton changepasswd;
    private javax.swing.JButton discharge;
    private javax.swing.JButton existing;
    private javax.swing.JLabel host;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newentry;
    private javax.swing.JButton orgdetails;
    private javax.swing.JButton signout;
    // End of variables declaration//GEN-END:variables
}
