/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bill;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author m17
 */
public class print_bill extends javax.swing.JFrame {

    /* my coce starts here */
    
    String reg_num,status;
    public void get_reg_num(String s) {
        reg_num = s;
        r.setText(reg_num);
        String u ="asd",z="ad",x="dd";
        String u1 ="123",z1="12",x1="22";
//        System.out.println(reg_num);
        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement ss=(Statement)con.createStatement();
            ResultSet rs,rs1;
            
            rs = ss.executeQuery("Select * from patient where Reg_No = '"+reg_num+"'");
            while(rs.next()){
                u = rs.getString("Name");
                z = rs.getString("Entry_Date");
                x = rs.getString("Exit_Date");
            }
            rs1 = ss.executeQuery("Select * from charges where Reg_No = '"+reg_num+"'");
            while(rs1.next()){
                u1 = rs1.getString("Init_Charge");
                z1 = rs1.getString("Doctor_Charge");
                x1 = rs1.getString("Medical_Charge");
            }
        }catch (Exception e) {
        }
        name.setText(u);
        da.setText(z);
        dd.setText(x);
        init.setText(u1);
        dc.setText(z1);
        mc.setText(x1);
        int temp = Integer.parseInt(u1)+Integer.parseInt(z1)+Integer.parseInt(x1);
        tc.setText(""+temp+"");
    }
    
    public void get_status(String s) {
        status = s;
//        System.out.println(status);
        sta.setText(status);
    }
    /**
     * Creates new form print_bill
     */
    public print_bill() {
        initComponents();
        String p="gh";
        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement s=(Statement)con.createStatement();
            ResultSet rs;
            rs = s.executeQuery("Select * from organization");
            while(rs.next()){
                p = rs.getString("Org_Name");
            }
            
        }catch (Exception e) {
        }
        host.setText(p);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        int screenWidth = dimension.width;
        int screenHeight = dimension.height;
        setSize(dimension);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
        JLabel background=new JLabel(new ImageIcon(getClass().getResource("/bill/bkground.jpg")));
        add(background);
        background.setLayout(new FlowLayout());
        Date date = new Date();
        jLabel26.setText(date.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        host = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        r = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        da = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        init = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        mc = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dc = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tc = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        sta = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 560));
        getContentPane().setLayout(null);

        host.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        host.setForeground(new java.awt.Color(255, 255, 0));
        host.setText("D.M.H. Hospital");
        getContentPane().add(host);
        host.setBounds(490, 30, 236, 41);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Patient's Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 170, 150, 22);

        name.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        name.setForeground(new java.awt.Color(0, 204, 0));
        name.setText("Name");
        getContentPane().add(name);
        name.setBounds(670, 170, 160, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Regestration Number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(370, 200, 190, 22);

        r.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r.setForeground(new java.awt.Color(0, 204, 0));
        r.setText("Reg_num");
        getContentPane().add(r);
        r.setBounds(670, 200, 170, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Date of Admission");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(369, 230, 170, 22);

        da.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        da.setForeground(new java.awt.Color(0, 204, 0));
        da.setText("date");
        getContentPane().add(da);
        da.setBounds(670, 230, 200, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Date of Discharge");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(369, 260, 170, 22);

        dd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dd.setForeground(new java.awt.Color(0, 204, 0));
        dd.setText("date");
        getContentPane().add(dd);
        dd.setBounds(670, 260, 170, 22);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 340, 1080, 10);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Initial Charge");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(380, 370, 110, 22);

        init.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        init.setForeground(new java.awt.Color(0, 204, 0));
        init.setText("amount");
        getContentPane().add(init);
        init.setBounds(670, 370, 140, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("Medical Charge");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(380, 400, 130, 22);

        mc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mc.setForeground(new java.awt.Color(0, 204, 0));
        mc.setText("amount");
        getContentPane().add(mc);
        mc.setBounds(670, 400, 160, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Doctor's Charge");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(380, 430, 130, 22);

        dc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dc.setForeground(new java.awt.Color(0, 204, 0));
        dc.setText("amount");
        getContentPane().add(dc);
        dc.setBounds(670, 430, 140, 22);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("Total Amount");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(380, 460, 120, 22);

        tc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tc.setForeground(new java.awt.Color(0, 204, 0));
        tc.setText("sum");
        getContentPane().add(tc);
        tc.setBounds(670, 460, 150, 22);

        jLabel18.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 0));
        jLabel18.setText("Depositor's Signature");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(230, 520, 180, 22);

        jLabel19.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 0));
        jLabel19.setText("Cashier's Signature");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(690, 520, 170, 22);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(401, 570, 90, 25);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("Bill Number");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(240, 100, 100, 22);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 204, 0));
        jLabel21.setText("Number");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(390, 100, 70, 22);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(570, 570, 110, 25);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("Status");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(370, 290, 100, 14);

        sta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sta.setForeground(new java.awt.Color(0, 204, 0));
        sta.setText("Status");
        getContentPane().add(sta);
        sta.setBounds(670, 290, 150, 22);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 0, 0));
        jLabel24.setText("Date");
        getContentPane().add(jLabel24);
        jLabel24.setBounds(790, 100, 40, 20);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 204, 0));
        jLabel25.setText("date");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(860, 100, 50, 22);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 102, 153));
        jLabel26.setText("jLabel26");
        getContentPane().add(jLabel26);
        jLabel26.setBounds(860, 40, 350, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        new homepage().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement ss =(Statement)con.createStatement();
            ss.executeUpdate("Delete from patient where Reg_No= '"+reg_num+"'");
        }catch (Exception e) {
        }
        setVisible(false);
        new homepage().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel da;
    private javax.swing.JLabel dc;
    private javax.swing.JLabel dd;
    private javax.swing.JLabel host;
    private javax.swing.JLabel init;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mc;
    private javax.swing.JLabel name;
    private javax.swing.JLabel r;
    private javax.swing.JLabel sta;
    private javax.swing.JLabel tc;
    // End of variables declaration//GEN-END:variables
}
