/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bill;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author m17
 */
public class show_bed extends javax.swing.JFrame {

    /**
     * Creates new form show_bed
     */
    String reg_num,resp1;
    String option;
    
    public show_bed() {
        initComponents();
        String p="gh";
        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement s=(Statement)con.createStatement();
            ResultSet rs;
            rs = s.executeQuery("Select * from organization");
            while(rs.next()){
                p = rs.getString("Org_Name");
            }
            
        }catch (Exception e) {
        }
        host.setText(p);
        int v=0,o=0;
        String u="asd",z="asd",m="asd";
        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement s=(Statement)con.createStatement();
            ResultSet rs;
            
            rs = s.executeQuery("Select * from bed");
            while(rs.next()){
                u = rs.getString("Status");
                z = rs.getString("Location");
                if(u.compareTo("vacant") == 0 && z.compareTo("General Ward") == 0){
                    v++;
                }else if(u.compareTo("vacant") == 0 && z.compareTo("I.C.U.") == 0){
                    o++;
                }
            }
        }catch (Exception e) {
        }
        gw.setText(""+v+"");
        icu.setText(""+o+"");
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        int screenWidth = dimension.width;
        int screenHeight = dimension.height;
        setSize(dimension);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
        JLabel background=new JLabel(new ImageIcon(getClass().getResource("/bill/bkground.jpg")));
        add(background);
        background.setLayout(new FlowLayout());
        Date date = new Date();
        jLabel10.setText(date.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        host = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        gw = new javax.swing.JLabel();
        icu = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        r = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        bn = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(580, 480));
        getContentPane().setLayout(null);

        host.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        host.setForeground(new java.awt.Color(255, 255, 0));
        host.setText("D.M.H. Hospital");
        getContentPane().add(host);
        host.setBounds(380, 30, 235, 41);

        jLabel2.setBackground(new java.awt.Color(153, 153, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Number of Vacant Beds ---");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 100, 280, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("In General Ward");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(400, 130, 160, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("In ICU");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(490, 160, 60, 22);

        gw.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        gw.setForeground(new java.awt.Color(0, 204, 0));
        gw.setText("cnt1");
        getContentPane().add(gw);
        gw.setBounds(630, 130, 60, 22);

        icu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        icu.setForeground(new java.awt.Color(0, 204, 0));
        icu.setText("cnt2");
        getContentPane().add(icu);
        icu.setBounds(630, 160, 60, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("To get location of a patient , enter Registration Number");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 200, 500, 30);

        r.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        r.setForeground(new java.awt.Color(0, 204, 0));
        getContentPane().add(r);
        r.setBounds(610, 200, 130, 28);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 250, 80, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Enter location of Bed");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 310, 200, 17);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(153, 0, 153));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "General Ward", "ICU" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(570, 310, 111, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Enter Bed Number");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(280, 390, 170, 17);

        bn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bn.setForeground(new java.awt.Color(0, 204, 0));
        getContentPane().add(bn);
        bn.setBounds(570, 390, 120, 28);

        jButton2.setBackground(new java.awt.Color(255, 102, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Check Status");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(480, 450, 140, 25);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 102, 153));
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(720, 40, 350, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        reg_num = r.getText();
        String p="asd",q="asd";
        int f =0;
        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement s=(Statement)con.createStatement();
            ResultSet rs;
            rs = s.executeQuery("Select * from patient");
            while(rs.next()){
                p = rs.getString("Reg_No");
                if(p.compareTo(reg_num) == 0){
                    f = 1;
                    break;
                }
                
            }
            
        }catch (Exception e) {
    }
        if (f == 0) {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"Registration Number does not exist.","Warning",JOptionPane.WARNING_MESSAGE);
        } else {
            try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement s=(Statement)con.createStatement();
            ResultSet rs;
            rs = s.executeQuery("Select * from track where Reg_No = '"+reg_num+"'");
            while(rs.next()){
                p = rs.getString("Bed_No");
                q = rs.getString("Ward_Type");
            }
            
        }catch (Exception e) {
    }       
            resp1 = "patient is at bed number " + p +" in " + q + " ";
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,resp1);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String temp = bn.getText(),p="asd";
        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement s=(Statement)con.createStatement();
            ResultSet rs;
            rs = s.executeQuery("Select * from bed where Bed_No = '"+temp+"'");
            while(rs.next()){
                p = rs.getString("Status");
            }
            
        }catch (Exception e) {
    }
        if (p.compareTo("vacant") == 0) {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"Selected Bed is vacant.");
        } else {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"Selected Bed is occupied");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        option = jComboBox1.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bn;
    private javax.swing.JLabel gw;
    private javax.swing.JLabel host;
    private javax.swing.JLabel icu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField r;
    // End of variables declaration//GEN-END:variables
}
