/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bill;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author m17
 */
public class update extends javax.swing.JFrame {
    /* my code starts here */
    String reg_num;
    String option = "";
    String medical,doctor;
    String A = "Shift Patient from General Ward to ICU";
    String B = "Shift Patient from ICU to General Ward";
    void get_reg(String s) {
        reg_num = s;
    }

    /**
     * Creates new form update
     */
    public update() {
        initComponents();
        String p="gh";
        try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement s=(Statement)con.createStatement();
            ResultSet rs;
            rs = s.executeQuery("Select * from organization");
            while(rs.next()){
                p = rs.getString("Org_Name");
            }
            
        }catch (Exception e) {
        }
        host.setText(p);
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension dimension = tk.getScreenSize();
        int screenWidth = dimension.width;
        int screenHeight = dimension.height;
        setSize(dimension);
        setLocationRelativeTo(null);
        setLayout(new BorderLayout());
        JLabel background=new JLabel(new ImageIcon(getClass().getResource("/bill/bkground.jpg")));
        add(background);
        background.setLayout(new FlowLayout());
        Date date = new Date();
        jLabel7.setText(date.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        host = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        Reg_no = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(685, 515));
        getContentPane().setLayout(null);

        host.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        host.setForeground(new java.awt.Color(255, 255, 51));
        host.setText("D.M.H. Hospital");
        getContentPane().add(host);
        host.setBounds(480, 60, 238, 41);

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Patient's Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 170, 174, 24);

        jLabel2.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Registration Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 210, 300, 27);

        jLabel3.setFont(new java.awt.Font("Vani", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Current Total Charge");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 250, 240, 41);

        jLabel4.setFont(new java.awt.Font("Utsaah", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Amount");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(690, 250, 110, 41);

        jLabel5.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 0));
        jLabel5.setText("Add Medical Charge");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(380, 430, 170, 30);

        mc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mc.setForeground(new java.awt.Color(255, 51, 0));
        mc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mcActionPerformed(evt);
            }
        });
        getContentPane().add(mc);
        mc.setBounds(590, 430, 94, 23);

        jLabel6.setFont(new java.awt.Font("Utsaah", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 255, 0));
        jLabel6.setText("Add Doctor's Charge");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(377, 480, 170, 28);

        dc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dc.setForeground(new java.awt.Color(255, 51, 0));
        dc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dcActionPerformed(evt);
            }
        });
        getContentPane().add(dc);
        dc.setBounds(590, 480, 94, 23);

        jButton1.setBackground(new java.awt.Color(51, 255, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Go");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(730, 330, 90, 25);

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 560, 110, 25);

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(620, 560, 110, 25);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 51, 51));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<None>", "Shift Patient from General Ward to ICU", "Shift Patient from ICU to General Ward" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(400, 330, 264, 23);

        jLabel8.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 204, 0));
        jLabel8.setText("Name");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(690, 160, 100, 32);

        Reg_no.setFont(new java.awt.Font("Simplified Arabic Fixed", 1, 24)); // NOI18N
        Reg_no.setForeground(new java.awt.Color(51, 204, 0));
        Reg_no.setText("aaaaaaaaaaaaaaaa");
        getContentPane().add(Reg_no);
        Reg_no.setBounds(690, 210, 170, 27);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 102));
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(780, 50, 330, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dcActionPerformed
        
    }//GEN-LAST:event_dcActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        option = jComboBox1.getSelectedItem().toString();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (option.equals(A)) {
            GW_to_ICU obj1 = new GW_to_ICU();
            obj1.get(reg_num);
            obj1.setVisible(true);
        } else if (option.equals(B)){
            ICU_to_GW obj2 = new ICU_to_GW();
            obj2.get(reg_num);
            obj2.setVisible(true);
        } else {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"None is Selected.","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String a = "hgj", b="asda";
        medical = mc.getText();
        doctor = dc.getText();
        if (medical.length() == 0 || doctor.length() == 0) {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame,"Medical Charge field or Doctor's Charge field is empty","Warning",
            JOptionPane.WARNING_MESSAGE);
        } else {
            try {
            Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/Hospital", "root", "qwerty");
            Statement s=(Statement)con.createStatement();
            ResultSet rs;
            rs = s.executeQuery("Select * from charges where Reg_No = '"+reg_num+"'");
            while(rs.next()){
                a = rs.getString("Doctor_Charge");
                b = rs.getString("Medical_Charge");
            }         
            int t1 = Integer.parseInt(a)+Integer.parseInt(doctor);
            doctor = "" + t1 + "";
            int t2 = Integer.parseInt(b)+Integer.parseInt(medical);
            medical = "" + t2 + "";
            s.executeUpdate("Update charges SET Doctor_Charge ='"+doctor+"', Medical_Charge = '"+medical+"' where Reg_No = '"+reg_num+"'" );
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "Entered Fields are updated");
            setVisible(false);
            new homepage().setVisible(true);
        } catch (Exception e) { 
        }
            setVisible(false);
            new homepage().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setVisible(false);
        new homepage().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void mcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mcActionPerformed
        
    }//GEN-LAST:event_mcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Reg_no;
    private javax.swing.JTextField dc;
    private javax.swing.JLabel host;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField mc;
    // End of variables declaration//GEN-END:variables

}
